version: '3.7'

services:

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - TZ=Europe/Madrid
      - SUBDOMAINS=${SUBDOMAINS} # pagina_ejemplo
      - TOKEN=${TOKEN}
    volumes:
      - ./conf/duckdns:/config
    restart: unless-stopped

  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - URL=${DOMINIO}           #pagina_ejemplo.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${TOKEN}
      - SUBDOMAINS=www,
      #- DNSPLUGIN=cloudflare
    volumes:
      - ./conf/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
      - "4443:443/tcp"
    environment:
      - TZ=Europe/Madrid
      - WEBPASSWORD=${PASSWORD}
    volumes:
      - ./conf/pihole/etc-pihole:/etc/pihole
      - ./conf/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN    
    restart: unless-stopped