version: '3.7'

services:

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - TZ=Europe/Madrid
      - SUBDOMAINS=${SUBDOMAINS} # pagina_ejemplo
      - TOKEN=${TOKEN}
    volumes:
      - ./conf/duckdns:/config
    restart: unless-stopped

  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - URL=${DOMINIO}           #pagina_ejemplo.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${TOKEN}
      - SUBDOMAINS=www,
      #- DNSPLUGIN=cloudflare
    volumes:
      - ./conf/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 9000:9000
